version: 2

models:
  - name: age_category_analysis
    description: "Analysis of age groups and purchase patterns"
    columns:
      - name: age_group
        description: "Customer age groups from youngest to oldest"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 18
              max_value: 100
              strictly: true  # Wyklucza 18 i 100 jako wartości brzegowe

      - name: Category
        description: "Product category"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['Clothing', 'Accessories', 'Footwear', 'Outerwear']

      - name: Purchase_count
        description: "Number of purchases in category"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_not_be_zero
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: "integer"

      - name: percentage_in_age_group
        description: "Percentage distribution across age groups"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100
          - dbt_expectations.expect_table_sum_to_equal:
              column_name: percentage_in_age_group
              sum_total: 100
              tolerance: 0.5  # Zwiększona tolerancja dla zaokrągleń

  - name: payment_method_analysis
    description: "Payment method frequency and revenue impact"
    columns:
      - name: Payment_Method
        description: "Type of payment method used"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['Credit Card', 'PayPal', 'Cash', 'Debit Card', 'Venmo', 'Bank Transfer']

      - name: transaction_count
        description: "Number of transactions per method"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_not_be_zero
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: "integer"

      - name: total_revenue
        description: "Total revenue per payment method"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0.01
              max_value: 1000000  # Zmniejszona maksymalna wartość
              row_condition: "total_revenue IS NOT NULL"

      - name: avg_order_revenue
        description: "Average order value per payment method"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0.01
              max_value: 10000
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: "numeric"  # Zmienione na numeric dla wartości dziesiętnych

      - name: percentage_of_orders
        description: "Percentage share of payment methods"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100
          - dbt_expectations.expect_table_sum_to_equal:
              column_name: percentage_of_orders
              sum_total: 100
              tolerance: 1.0  # Zwiększona tolerancja
      - name: subscription_impact
        columns:
          - name: total_revenue
            tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_between:
                min_value: 0
